/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfCommandFlight.java
 *
 * Created on 6-okt-2011, 12:45:05
 */
package atc.gui;

import atc.logic.Flightplan;

/**
 *
 * @author Mateusz
 */
public class jfCommandFlight extends javax.swing.JDialog {
    private Flightplan flightplan;
    
    /** Creates new form jfCommandFlight */
    public jfCommandFlight(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setFlightplan(Flightplan flightplan) {
        this.flightplan = flightplan;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxFlight = new javax.swing.JComboBox();
        btChangeParameter = new javax.swing.JButton();
        lblChangeSpeedTo = new javax.swing.JLabel();
        lblFlight = new javax.swing.JLabel();
        lblChangeHeightTo = new javax.swing.JLabel();
        txtChangeHeightTo = new javax.swing.JTextField();
        txtChangeSpeedTo = new javax.swing.JTextField();
        lblChangeDirectionTo = new javax.swing.JLabel();
        txtChangeDirectionTo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbxFlight.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btChangeParameter.setText("Change parameter");
        btChangeParameter.setName(""); // NOI18N
        btChangeParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeParameterActionPerformed(evt);
            }
        });

        lblChangeSpeedTo.setText("Change Speed to: ");

        lblFlight.setText("Flight: ");

        lblChangeHeightTo.setText("Change Height to: ");

        txtChangeHeightTo.setToolTipText("");

        lblChangeDirectionTo.setText("Change Direction to: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFlight)
                            .addComponent(lblChangeDirectionTo)
                            .addComponent(lblChangeHeightTo)
                            .addComponent(lblChangeSpeedTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxFlight, 0, 84, Short.MAX_VALUE)
                            .addComponent(txtChangeSpeedTo)
                            .addComponent(txtChangeHeightTo)
                            .addComponent(txtChangeDirectionTo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btChangeParameter)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlight)
                    .addComponent(cbxFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangeSpeedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChangeSpeedTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangeHeightTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChangeHeightTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChangeDirectionTo)
                    .addComponent(txtChangeDirectionTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btChangeParameter)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btChangeParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeParameterActionPerformed
        if (txtChangeSpeedTo.getText() != null)
        {
            flightplan.getAirplane().ChangeSpeed(Integer.parseInt(txtChangeSpeedTo.getText()));
        }
        
        if (txtChangeDirectionTo.getText() != null)
        {
            flightplan.getAirplane().ChangeDirection(Integer.parseInt(txtChangeDirectionTo.getText()));
        }
        
        if (txtChangeHeightTo.getText() != null)
        {
            flightplan.getAirplane().ChangeAltitude(Integer.parseInt(txtChangeHeightTo.getText()));
        }
    }//GEN-LAST:event_btChangeParameterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jfCommandFlight dialog = new jfCommandFlight(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChangeParameter;
    private javax.swing.JComboBox cbxFlight;
    private javax.swing.JLabel lblChangeDirectionTo;
    private javax.swing.JLabel lblChangeHeightTo;
    private javax.swing.JLabel lblChangeSpeedTo;
    private javax.swing.JLabel lblFlight;
    private javax.swing.JTextField txtChangeDirectionTo;
    private javax.swing.JTextField txtChangeHeightTo;
    private javax.swing.JTextField txtChangeSpeedTo;
    // End of variables declaration//GEN-END:variables
}
