/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfCommandFlight.java
 *
 * Created on 6-okt-2011, 12:45:05
 */
package atc.gui;

import atc.logic.Airplane.Statusses;
import atc.logic.AssignmentException;
import atc.logic.Flightplan;
import atc.logic.Runway;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import javax.swing.Timer;
import javax.swing.JOptionPane;

/**
 *
 * @author Johan & Mateusz
 */
public class jfCommandFlight extends javax.swing.JDialog {
    private Flightplan flightplan;
    private final Timer timer;
    
    /** Creates new form jfCommandFlight */
    public jfCommandFlight(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.timer = new Timer(50, new ActionListener() {
                    public void actionPerformed(ActionEvent event) {
                        if (flightplan.getAirplane().getStatus() == Statusses.INLANDINGQUEUE) {
                            btnLandFlight.setEnabled(true);
                        }
                        else {
                            btnLandFlight.setEnabled(false);
                        }
                    }
                });
                timer.start();
    }

    public void setFlightplan(Flightplan flightplan) {
        this.flightplan = flightplan;
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btChangeParameter = new javax.swing.JButton();
        lblChangeSpeedTo = new javax.swing.JLabel();
        lblChangeHeightTo = new javax.swing.JLabel();
        txtChangeSpeedTo = new javax.swing.JTextField();
        lblChangeDirectionTo = new javax.swing.JLabel();
        txtChangeDirectionTo = new javax.swing.JTextField();
        tfFlightlevel = new javax.swing.JComboBox();
        btnLandFlight = new javax.swing.JButton();
        btnTakeOffFlight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btChangeParameter.setText("Change parameter");
        btChangeParameter.setName(""); // NOI18N
        btChangeParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeParameterActionPerformed(evt);
            }
        });

        lblChangeSpeedTo.setText("Change Speed to: ");

        lblChangeHeightTo.setText("Change Flight Level to: ");

        lblChangeDirectionTo.setText("Change Direction to: ");

        tfFlightlevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Flighlevel One", "Flightlevel Two", "Flightlevel Three" }));

        btnLandFlight.setText("Land flight");
        btnLandFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLandFlightActionPerformed(evt);
            }
        });

        btnTakeOffFlight.setText("Takeoff Flight");
        btnTakeOffFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakeOffFlightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtChangeDirectionTo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfFlightlevel, javax.swing.GroupLayout.Alignment.LEADING, 0, 148, Short.MAX_VALUE)
                            .addComponent(lblChangeSpeedTo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChangeSpeedTo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(lblChangeHeightTo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(239, 239, 239))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblChangeDirectionTo)
                        .addContainerGap(285, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTakeOffFlight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLandFlight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btChangeParameter)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChangeSpeedTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChangeSpeedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChangeHeightTo)
                .addGap(8, 8, 8)
                .addComponent(tfFlightlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblChangeDirectionTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChangeDirectionTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btChangeParameter)
                    .addComponent(btnLandFlight)
                    .addComponent(btnTakeOffFlight))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btChangeParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeParameterActionPerformed
        if (!"".equals(txtChangeSpeedTo.getText()))
        {
            flightplan.getAirplane().SetAimedSpeed(Integer.parseInt(txtChangeSpeedTo.getText()));
        }
        
        if (!"".equals(txtChangeDirectionTo.getText()))
        {
            flightplan.getAirplane().SetAimedDirection(Integer.parseInt(txtChangeDirectionTo.getText()));
        }
        
        if (!"".equals(tfFlightlevel.getSelectedItem()))
        {
            flightplan.getAirplane().SetAimedAltitude(tfFlightlevel.getSelectedIndex() + 1);
        }
        
        WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);
    }//GEN-LAST:event_btChangeParameterActionPerformed

    private void btnLandFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandFlightActionPerformed
        // TODO add your handling code here:
        
        try {
            atc2.acc.LandFlight(flightplan);
        } catch (AssignmentException ex) {
            JOptionPane.showMessageDialog(this, "There are no runways available at destination airport.");
        }
    }//GEN-LAST:event_btnLandFlightActionPerformed

    private void btnTakeOffFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeOffFlightActionPerformed
        flightplan.getAirplane().setStatus(Statusses.TAKINGOFF);
        System.out.println("TakeOff");
    }//GEN-LAST:event_btnTakeOffFlightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jfCommandFlight dialog = new jfCommandFlight(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChangeParameter;
    private javax.swing.JButton btnLandFlight;
    private javax.swing.JButton btnTakeOffFlight;
    private javax.swing.JLabel lblChangeDirectionTo;
    private javax.swing.JLabel lblChangeHeightTo;
    private javax.swing.JLabel lblChangeSpeedTo;
    private javax.swing.JComboBox tfFlightlevel;
    private javax.swing.JTextField txtChangeDirectionTo;
    private javax.swing.JTextField txtChangeSpeedTo;
    // End of variables declaration//GEN-END:variables
}
