/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfCommandFlight.java
 *
 * Created on 6-okt-2011, 12:45:05
 */
package atc.gui;

import atc.logic.Flightplan;

/**
 *
 * @author Johan & Mateusz
 */
public class jfCommandFlight extends javax.swing.JDialog {
    private Flightplan flightplan;
    
    /** Creates new form jfCommandFlight */
    public jfCommandFlight(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void setFlightplan(Flightplan flightplan) {
        this.flightplan = flightplan;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btChangeParameter = new javax.swing.JButton();
        lblChangeSpeedTo = new javax.swing.JLabel();
        lblChangeHeightTo = new javax.swing.JLabel();
        txtChangeSpeedTo = new javax.swing.JTextField();
        lblChangeDirectionTo = new javax.swing.JLabel();
        txtChangeDirectionTo = new javax.swing.JTextField();
        tfFlightlevel = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btChangeParameter.setText("Change parameter");
        btChangeParameter.setName(""); // NOI18N
        btChangeParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeParameterActionPerformed(evt);
            }
        });

        lblChangeSpeedTo.setText("Change Speed to: ");

        lblChangeHeightTo.setText("Change Flight Level to: ");

        lblChangeDirectionTo.setText("Change Direction to: ");

        tfFlightlevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Flighlevel One", "Flightlevel Two", "Flightlevel Three" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtChangeDirectionTo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addGap(239, 239, 239))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tfFlightlevel, 0, 151, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblChangeSpeedTo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtChangeSpeedTo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblChangeHeightTo)))
                .addGap(239, 239, 239))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChangeDirectionTo)
                .addContainerGap(253, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(btChangeParameter)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChangeSpeedTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChangeSpeedTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChangeHeightTo)
                .addGap(8, 8, 8)
                .addComponent(tfFlightlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblChangeDirectionTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChangeDirectionTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btChangeParameter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btChangeParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeParameterActionPerformed
        if (!"".equals(txtChangeSpeedTo.getText()))
        {
            flightplan.getAirplane().SetAimedSpeed(Integer.parseInt(txtChangeSpeedTo.getText()));
        }
        
        if (!"".equals(txtChangeDirectionTo.getText()))
        {
            flightplan.getAirplane().SetAimedDirection(Integer.parseInt(txtChangeDirectionTo.getText()));
        }
        
        if (!"".equals(tfFlightlevel.getSelectedItem()))
        {
            flightplan.getAirplane().SetAimedAltitude(tfFlightlevel.getSelectedIndex() + 1);
        }
    }//GEN-LAST:event_btChangeParameterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfCommandFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                jfCommandFlight dialog = new jfCommandFlight(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChangeParameter;
    private javax.swing.JLabel lblChangeDirectionTo;
    private javax.swing.JLabel lblChangeHeightTo;
    private javax.swing.JLabel lblChangeSpeedTo;
    private javax.swing.JComboBox tfFlightlevel;
    private javax.swing.JTextField txtChangeDirectionTo;
    private javax.swing.JTextField txtChangeSpeedTo;
    // End of variables declaration//GEN-END:variables
}
